### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Drulac** [romgrk/node-gtk#152]
Hello :smile: 

there is a `UnhandledPromiseRejectionWarning` inside `internal/process/task_queues.js` at line 86 : 
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Promise (/scripts/convertToMD/md2html.js:138:6)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Object.main (/scripts/convertToMD/node_modules/node-gtk/lib/overrides/Gtk-3.0.js:40:11)
    at AsyncFunction.window.on (/scripts/convertToMD/front/app/term.js:157:6)
    at Object.<anonymous> (/scripts/convertToMD/front/app/term.js:189:8)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
(node:15506) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:15506) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It's not urgent

**Comment by romgrk** [comment]
Thanks for the report! Could you also provide steps for how to reproduce the issue?

**Comment by Drulac** [comment]
maybe in 2 month after my exams if I remember how to, I'm busy actually :S

**Comment by romgrk** [comment]
Got it, re-open if you can provide the steps :)
