### ISSUE TITLE
Core dump when method is called with invalid type

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#18]
https://github.com/romgrk/node-gtk/blob/master/tests/method_call__invalid_type.js

**Comment by romgrk** [comment]
[Type checking is working](https://github.com/romgrk/node-gtk/commit/a688edd8145033bdee5b44eebb7d98aac81b7e12) :D
Besides, the error message is quite helpful to help determine the correct type:
```console
$ node ./tests/function_call__invalid_type.js
Soup.Message#setUri
Got expected error: TypeError: Expected argument of type Soup.URI for parameter uri
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:15:11)
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:29:5)
    at Object.<anonymous> (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19) 

Gtk.init(45)
Got expected error: TypeError: Expected argument of type String[] for parameter argv
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:19:7)
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:29:5)
    at Object.<anonymous> (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19) 

glib.random_int_range(0, 'string')
Got expected error: TypeError: Expected argument of type Number for parameter end
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:23:8)
    at test (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:29:5)
    at Object.<anonymous> (/home/romgrk/github/node-gtk/tests/function_call__invalid_type.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19) 
```
