### ISSUE TITLE
GObject: new with invalid property fails

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#219]
```js
const label = new GtkLabel({ markup: 'content' })
```

```
Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff5200f9c in GNodeJS::CreateGObjectFromObject (Python Exception <class 'gdb.error'> No type named TypeNode.: 
gtype=, object=...) at ../src/gobject.cc:60
60	        g_value_init(&values[i], value_gtype);
(gdb) bt
#0  0x00007ffff5200f9c in GNodeJS::CreateGObjectFromObject(GType, v8::Local<v8::Value>)Python Exception <class 'gdb.error'> No type named TypeNode.: 

    (gtype=, object=...) at ../src/gobject.cc:60
#1  0x00007ffff5201402 in GNodeJS::GObjectConstructor(Nan::FunctionCallbackInfo<v8::Value> const&)
    (info=...) at /home/romgrk/.cache/node-gyp/14.8.0/include/node/v8.h:337
#2  0x00007ffff5200b58 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)
    (info=...) at ../../nan/nan_callbacks_12_inl.h:176
#3  0x0000000000bdf075 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#4  0x0000000000bdf67f in v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) ()
#5  0x0000000000bdfca6 in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) ()
#6  0x00000000013ce139 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit ()
#7  0x0000000001363561 in Builtins_JSBuiltinsConstructStub ()
#8  0x00000a122ed3bd81 in  ()
#9  0x00000a122ed3bd81 in  ()
#10 0x0000000600000000 in  ()
#11 0x000018a99d900541 in  ()
#12 0x0000170fb888bc59 in  ()
#13 0x0000170fb888c289 in  ()
#14 0x0000000100000000 in  ()
#15 0x000017a81939dba9 in  ()
#16 0x0000000000000024 in  ()
#17 0x00007fffffffa258 in  ()
#18 0x000000000144bce3 in Builtins_ConstructHandler ()

```

**Comment by romgrk** [comment]
NA, was testing against old version of node-gtk.
