### ISSUE TITLE
Core dump in examples/editor.js

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#44]
```js
const gi = require('../');
const Gtk = gi.require('Gtk');
const GtkSource = gi.require('GtkSource', '3.0')
const common = require('./__common__.js')

Gtk.init()

const textView = new GtkSource.View()
const buffer = textView.getBuffer()

buffer.placeCursor(buffer.getEndIter())
```

Output:
```
[1]    20786 segmentation fault  rr record -n node tests/gtk_text_buffer_place_cursor.js
```

**Comment by romgrk** [comment]
Looks like an GIR bug, the JS function call is `gtkBuffer.placeCursor()`, but the C call-stack shows `gtk_text_buffer_select_range()` being called. The name is in the bindings, but the C function address might be wrong.

**Comment by romgrk** [comment]
After review, it doesn't seem to be a GIR bug: the FFI structure contains the correct address.
Call stack:
```
#0  0x00007feda569a2de in  () at /usr/lib/libgtk-3.so.0
#1  0x00007feda569a50d in  () at /usr/lib/libgtk-3.so.0
#2  0x00007feda569e6df in  () at /usr/lib/libgtk-3.so.0
#3  0x00007feda56a19b8 in gtk_text_buffer_select_range () at /usr/lib/libgtk-3.so.0
#4  0x00007fed8f5621c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#5  0x00007fed8f561c2a in ffi_call () at /usr/lib/libffi.so.6
#6  0x00007feda5d13e7a in GNodeJS::FunctionCall(GNodeJS::FunctionInfo*, Nan::FunctionCallbackInfo<v8::Value> const&, _GIArgument*, _GError**) (func=0x5577ca2e98b0, info=..., return_value=0x0, er
ror=0x0) at ../src/function.cc:253
```
GDB termui log:
```
   ┌──../src/function.cc─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
   │238             }                                                                                                                                                                            │
   │239         }                                                                                                                                                                                │
   │240                                                                                                                                                                                          │
   │241                                                                                                                                                                                          │
   │242         /*                                                                                                                                                                               │
   │243          * Third, make the actual ffi_call                                                                                                                                               │
   │244          */                                                                                                                                                                              │
   │245                                                                                                                                                                                          │
   │246         void *ffi_args[func->n_total_args];                                                                                                                                              │
   │247         for (int i = 0; i < func->n_total_args; i++)                                                                                                                                     │
   │248             ffi_args[i] = &total_arg_values[i];                                                                                                                                          │
   │249                                                                                                                                                                                          │
   │250                                                                                                                                                                                          │
   │251         GIArgument return_value_stack;                                                                                                                                                   │
   │252                                                                                                                                                                                          │
  >│253         ffi_call (&func->invoker.cif, FFI_FN (func->invoker.native_address),                                                                                                             │
   │254                   use_return_value ? return_value : &return_value_stack, ffi_args);                                                                                                      │
   │255                                                                                                                                                                                          │
   │256                                                                                                                                                                                          │
   │257         /*                                                                                                                                                                               │
   │258          * Fourth, convert the return value & OUT-arguments back to JS                                                                                                                   │
   │259          */                                                                                                                                                                              │
   │260                                                                                                                                                                                          │
   │261         GITypeInfo return_type;                                                                                                                                                          │
   │262         g_callable_info_load_return_type(gi_info, &return_type);                                                                                                                         │
   │263         GITransfer return_transfer = g_callable_info_get_caller_owns(gi_info);                                                                                                           │
   │264                                                                                                                                                                                          │
   │265         bool didThrow = error ? *error != NULL : error_stack != NULL;                                                                                                                    │
   │266                                                                                                                                                                                          │
   │267         // Return the value or throw the error, if any occured                                                                                                                           │
   │268         if (didThrow) {                                                                                                                                                                  │
   │269             jsReturnValue = Nan::Undefined();                                                                                                                                            │
   └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
extended-r Thread 20794.20794 In: GNodeJS::FunctionCall                                                                                                                  L253  PC: 0x7feda5d13e7a 
(rr) f 6
#6  0x00007feda5d13e7a in GNodeJS::FunctionCall (func=0x5577ca2e98b0, info=..., return_value=0x0, error=0x0) at ../src/function.cc:253
(rr) p func->invoker.native_address 
$6 = (gpointer) 0x7feda56a1a30 <gtk_text_buffer_place_cursor>
```

**Comment by romgrk** [comment]
Not reproducible anymore.
