### ISSUE TITLE
libgirepository-1.0.1.dylib image not found on OSX

### ISSUE THREAD

**Issue by codejamninja** [romgrk/node-gtk#98]
When I run the example on OSX I get the following error.

```sh
node ./examples/hello-gtk.js
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/codejamninja/Projects/node-gtk/lib/binding/node-v64-darwin-x64/node_gtk.node, 1): Library not loaded: /usr/local/opt/gobject-introspection/lib/libgirepository-1.0.1.dylib
  Referenced from: /Users/codejamninja/Projects/node-gtk/lib/binding/node-v64-darwin-x64/node_gtk.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/codejamninja/Projects/node-gtk/lib/native.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by codejamninja** [comment]
It turns out I didn't install gobject-introspection. This should be updated in the docs.

**Comment by wbrickner** [comment]
I'm having this issue after installing according to docs.
Any help?

**Comment by wbrickner** [comment]
This fails on at least as recently as Node v14.  Works at least as old as Node v12.
Just so it's on your radar.

**Comment by romgrk** [comment]
Can you run `brew install git node gobject-introspection gtk+3 cairo`, then `npm install node-gtk`, and post the output of the script in a new issue?
